# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.IntegerField()),
                ('year', models.IntegerField()),
                ('state_name', models.CharField(max_length=50)),
                ('county_name', models.CharField(max_length=50)),
                ('insecticide', models.FloatField()),
                ('herbicide', models.FloatField()),
                ('harvested', models.FloatField()),
                ('price', models.FloatField()),
                ('ag_p', models.FloatField()),
                ('corn_p', models.FloatField()),
                ('shannon', models.FloatField()),
                ('simpson', models.FloatField()),
                ('heatDay', models.FloatField()),
            ],
        ),
    ]
